name: Contexto
run-name: ¡Estoy aprendiendo a usar Contextos!
on: [push]

jobs:
  info-basica:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar info del repo
        run: |
          echo "Repositorio: ${{ github.repository }}"
          echo "Rama: ${{ github.ref_name }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
