name: Paso 6, Aprende a usar Variables de Entorno

on:
  workflow_dispatch:

env:
  DIA_DE_SEMANA: Lunes

jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA!"
        env:
          NOMBRE: Jano
