name: Saludo usando variables
run-name: ¡Estoy aprendiendo a usar Variables!
on: [push, pull_request]
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, $ {{ vars.NOMBRE }} . Hoy es $DIA_DE_SEMANA!"
